---
abstract: 'We are Czech CPAN authors.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Czech
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Acme::CPANAuthors: 0
  perl: 5.10.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Acme-CPANAuthors-Czech
  homepage: https://github.com/tupinek/Acme-CPANAuthors-Czech
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Acme-CPANAuthors-Czech
version: '0.19'
